# Configuración de GitHub Pages para Estudio Artesana
title: Estudio Artesana
description: Homepage profesional con panel de administración para Estudio Artesana
baseurl: "/EstudioArtesana" # Nombre del repositorio
url: "https://bluewants2fight-create.github.io" # URL base de GitHub Pages

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - node_modules
  - package*.json

# Include files that start with dots
include:
  - _config.yml

# Collections
collections_dir: pages

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: default
